name: intel
channels:
  - defaults
  - intel
dependencies:
  - intelpython3_full
  - pytorch
  - jupyter
  - pip
  - sphinx
  - yaml
  - zlib
  - zope.interface
  - pip:
    - dacite
    - dataclasses
    - gitdb2
    - gitpython
    - public
    - smmap2
    - sphinx-git
    - sphinx-rtd-theme
#    - ray
    - tables
    - aiohttp
    - psutil
    - setproctitle
    - grpcio
