name: intel
channels:
  - defaults
dependencies:
  - python=3.6
  - jupyter
  - pip
  - sphinx
  - yaml
  - zlib
  - zope
  - zope.interface
  - pip:
    - dacite
    - dataclasses
    - gitdb2
    - gitpython
    - public
    - smmap2
    - sphinx-git
    - sphinx-rtd-theme
    - ray
    - tables

